apiVersion: actions.cloudbees.io/v1alpha1
kind: action
name: hello-action
runs:
  using: composite
  steps:
    - name: "hello-action step"
      uses: docker://alpine:3.17
      shell: sh
      run: |
        echo "Hello from action."
